name: manyaran_system
description: Manyaran system provide smart home devices
version: 1.0.2+5

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  platform: ^3.1.0
  cupertino_icons: ^1.0.5
  package_info_plus: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  firebase_messaging: ^10.0.3
  firebase_database: ^7.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  adaptive_dialog: ^1.6.4+2
  intl: ^0.17.0
  recase: ^4.1.0
  google_sign_in: ^5.0.4
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter_local_notifications: ^6.0.0
  page_transition: ^2.0.9
  font_awesome_flutter: ^10.2.1
  time_ago_provider: ^4.2.0
  cached_network_image: ^3.2.2
  hexcolor: ^3.0.1
  card_swiper: ^2.0.4
  easy_image_viewer: ^1.2.0
  shimmer: ^2.0.0
  network_tools: ^3.0.0+3
  bot_toast: ^4.0.3
  glassmorphism: ^3.0.0
  wakelock: ^0.6.2
  http: ^0.13.5
  syncfusion_flutter_datepicker: ^20.3.56
  data_table_2: ^2.3.8
  flutter_staggered_animations: ^1.1.1
  flutter_custom_clippers: ^2.0.0
  fijkplayer: ^0.10.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/font/Poppins-Black.ttf
           weight: 900
         - asset: assets/font/Poppins-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: assets/font/Poppins-Bold.ttf
           weight: 700
         - asset: assets/font/Poppins-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/font/Poppins-ExtraBold.ttf
           weight: 800
         - asset: assets/font/Poppins-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: assets/font/Poppins-ExtraLight.ttf
           weight: 200
         - asset: assets/font/Poppins-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/font/Poppins-Italic.ttf
           weight: 400
           style: italic
         - asset: assets/font/Poppins-Light.ttf
           weight: 300
         - asset: assets/font/Poppins-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/font/Poppins-Medium.ttf
           weight: 500
         - asset: assets/font/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/font/Poppins-Regular.ttf
           weight: 400
         - asset: assets/font/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/font/Poppins-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/font/Poppins-Thin.ttf
           weight: 100
         - asset: assets/font/Poppins-ThinItalic.ttf
           weight: 100
           style: italic